"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.
"""


import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    
    a = 0
    b = 1

    nex = b

    sum = 0

    while nex <= n:
        nex = a + b
        a = b
        b = nex
        while nex <= n:
            if nex % 2 == 0:
                sum += nex
            nex = a + b
            a = b
            b = nex

    print(sum)


           